"""rFactor / rFactor 2 MOD generator.

rFactor uses plain-text files with ``key=value`` pairs.

Track layout (under ``GameData/Locations/<TrackID>/``):
  - ``<TrackID>.gdb``    – general track information (Series/Event metadata)
  - ``<TrackID>.scn``    – scene / layout file stub

Car layout (under ``GameData/Vehicles/<CarID>/``):
  - ``<CarID>.veh``      – vehicle identity and class
  - ``<CarID>.hdv``      – high-detail vehicle physics summary
  - ``<CarID>_engine.ini`` – engine parameters
"""

from __future__ import annotations

import re
from pathlib import Path

from race_mod_create.generators.base import BaseGenerator
from race_mod_create.models.car import Car
from race_mod_create.models.track import Track


def _to_id(name: str) -> str:
    """Convert a display name to a CamelCase-safe ASCII identifier."""
    words = re.sub(r"[^a-zA-Z0-9 ]+", " ", name).split()
    return "".join(w.capitalize() for w in words) if words else "Unknown"


class RFactorGenerator(BaseGenerator):
    """Generates rFactor–compatible MOD files."""

    simulator_name = "rFactor"

    # ------------------------------------------------------------------
    # Track
    # ------------------------------------------------------------------

    def generate_track(self, track: Track) -> Path:
        """Generate rFactor track mod files for *track*.

        Returns the root mod directory (``GameData/Locations/<id>``).
        """
        track_id = _to_id(track.name)
        root = self.output_dir / "GameData" / "Locations" / track_id
        self._ensure_dir(root)

        self._write_gdb(root, track_id, track)
        self._write_scn(root, track_id, track)

        return root

    def _write_gdb(self, root: Path, track_id: str, track: Track) -> None:
        sector_defs = ""
        cumulative = 0.0
        for i, sector in enumerate(track.sectors):
            cumulative += sector.length_m
            sector_defs += f"\nSector{i + 1}End = {cumulative / track.length_m:.6f}"

        content = (
            f"TrackName = {track.name}\n"
            f"EventName = {track.name} Circuit\n"
            f"TrackLocation = {track.location}\n"
            f"TrackLength = {track.length_m / 1000:.3f} km\n"
            f"PitBoxes = {track.pit_boxes}\n"
            f"Surface = {track.surface.value}\n"
            f"Author = {track.author}\n"
            f"Version = {track.version}\n"
            f"Description = {track.description}\n"
            f"{sector_defs}\n"
        )
        self._write_file(root / f"{track_id}.gdb", content)

    def _write_scn(self, root: Path, track_id: str, track: Track) -> None:
        content = (
            f"// {track.name} scene file – generated by RaceModCreate\n"
            f"SearchPath = {track_id}\n"
            f"MASFile = {track_id}.mas\n"
            "\n"
            "Group (\n"
            f"  TrackFile = {track_id}.tdf\n"
            ")\n"
        )
        self._write_file(root / f"{track_id}.scn", content)

    # ------------------------------------------------------------------
    # Car
    # ------------------------------------------------------------------

    def generate_car(self, car: Car) -> Path:
        """Generate rFactor car mod files for *car*.

        Returns the root mod directory (``GameData/Vehicles/<id>``).
        """
        car_id = _to_id(f"{car.manufacturer} {car.name}")
        root = self.output_dir / "GameData" / "Vehicles" / car_id
        self._ensure_dir(root)

        self._write_veh(root, car_id, car)
        self._write_hdv(root, car_id, car)
        self._write_engine_ini(root, car_id, car)

        return root

    def _write_veh(self, root: Path, car_id: str, car: Car) -> None:
        content = (
            "[VEHICLE]\n"
            f"Name = {car.manufacturer} {car.name}\n"
            f"Version = {car.version}\n"
            f"Type = {car.car_class.value}\n"
            f"Manufacturer = {car.manufacturer}\n"
            f"Model = {car.name}\n"
            f"Year = {car.year}\n"
            f"Author = {car.author}\n"
            f"Description = {car.description}\n"
        )
        self._write_file(root / f"{car_id}.veh", content)

    def _write_hdv(self, root: Path, car_id: str, car: Car) -> None:
        content = (
            "[GENERAL]\n"
            f"Mass = {car.mass_kg:.1f}           // kg, including driver\n"
            "Inertia = (1000.0, 1200.0, 150.0) // kg*m^2 (yaw, pitch, roll)\n"
            "\n"
            "[SUSPENSION]\n"
            "// Placeholder – tune for your car\n"
            "FrontWheelbase = 1.5\n"
            "RearWheelbase  = 1.5\n"
            "FrontTrackWidth = 1.5\n"
            "RearTrackWidth  = 1.5\n"
        )
        self._write_file(root / f"{car_id}.hdv", content)

    def _write_engine_ini(self, root: Path, car_id: str, car: Car) -> None:
        eng = car.engine
        content = (
            "[ENGINE]\n"
            f"Displacement = {eng.displacement_cc:.0f}  // cc\n"
            f"Cylinders = {eng.cylinders}\n"
            f"MaxPowerKW = {eng.max_power_kw:.1f}\n"
            f"MaxTorqueNM = {eng.max_torque_nm:.1f}\n"
            f"RevLimitRPM = {eng.max_rpm}\n"
            f"NaturallyAspirated = {'1' if eng.naturally_aspirated else '0'}\n"
        )
        self._write_file(root / f"{car_id}_engine.ini", content)
